### ISSUE TITLE
CCF in Endevor Explorer

### ISSUE THREAD

**Issue by db671543** [BroadcomMFD/cobol-control-flow#19]
I am using CCF 0.4.0 and have selected a Cobol source in Endevor explorer... when I ask for a control flow, it starts create the flow, but never ends. I will have to kill VS Code to stop it.
![2021-06-11_12-06-40](https://user-images.githubusercontent.com/57908777/121670253-7ec62580-caad-11eb-8f7f-ce501234bea2.png)

**Comment by db671543** [comment]
Cobol LS = 0.19.0

**Comment by zimlu02** [comment]
Hi Dana,

this should have been fixed by the latest COBOL LS release (0.20.0). Please let me know if you can still reproduce this issue or we can close the ticket.

Please note, there is another problem that when browsing and print listing COBOL files by Explorer for Endevor, COBOL LS still tries to parse it even though it contains not supported Endevor metadata. This is a different topic though, not related to CCF.
